<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://dispatcher.ws.master.cracking.uem.es/" name="Master_Dispatcher" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://dispatcher.ws.master.cracking.uem.es/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://dispatcher.ws.master.cracking.uem.es/" schemaLocation="../xsd/Master_Dispatcher.xsd"/>
    </xsd:schema>
  </types>
  <message name="dispatchRequest">
    <part name="parameters" element="tns:dispatch"/>
  </message>
  <portType name="Master_Dispatcher">
    <operation name="dispatch">
      <input message="tns:dispatchRequest"/>
    </operation>
  </portType>
  <binding name="Master_Dispatcher_PortBinding" type="tns:Master_Dispatcher">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="dispatch">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="Master_Dispatcher">
    <port name="Master_Dispatcher_Port" binding="tns:Master_Dispatcher_PortBinding">
      <soap:address location="http://10.10.10.10:7001/soa-infra/services/default/master_soa/Master_Dispatcher"/>
    </port>
  </service>
</definitions>
